#!/usr/bin/env bash

killall -q polybar
while pgrep -u $UID -x polybar >/dev/null; do
  sleep 1; done

feh --bg-center ~/.img/cwall.png

if [ "$(bspc query -M | wc -l)" = "1" ]; then
  polybar home -r &
  bspc monitor $PRIMARY_DISPLAY -d 1 2 3 4 5 6 7 8 9 10 11 12
else
  polybar work-center -r &
  polybar work-left -r &
  polybar work-right -r &
  bspc monitor $PRIMARY_DISPLAY -d 5 6 7 8
  bspc monitor $LEFT_DISPLAY -d 1 2 3 4
  bspc monitor $RIGHT_DISPLAY -d 9 10 11 12
fi

# bspc rule -a "VirtualBox Manager" desktop=^6
# bspc rule -a Chromium desktop=^9
# bspc rule -a Firefox desktop=^10
# bspc rule -a "TelegramDesktop" desktop=^12
# bspc rule -a "Zathura" desktop=^8 fullscreen=true
# virtualbox -r &
# firefox -r &
# chromium -r &
# telegram-desktop -r &

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
